name: medicine_reminder_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.0.2
  feather_icons: ^1.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.6
  freezed_annotation: ^2.2.0
  go_router: ^6.2.0
  google_fonts: ^4.0.3
  hooks_riverpod: ^2.3.2
  intl: ^0.18.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  json_annotation: ^4.8.0
  retrofit: ^4.0.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  go_router_builder: ^1.1.6
  isar_generator: ^3.0.5
  json_serializable: ^6.6.1
  retrofit_generator: ^6.0.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

